version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=devscout
    volumes:
      - ./pgdata:/app/postgresql/data
    ports:
      - "5432:5432"
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./:/app
    environment:
      - NODE_ENV=development
      - PORT=5000
      - PG_ORT=5432
      - HOST=db
      - USERNAME=postgres
      - PASSWORD=postgres
